apiVersion: v1
kind: Secret
metadata:
  name: postgres-bucket-uri-restore
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  POSTGRES_BUCKET_URI: {{ .Values.restore.bucket_uri | b64enc | quote }}
