apiVersion: v1
kind: Secret
metadata:
  name: postgres-bucket-uri
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  POSTGRES_BUCKET_URI: {{ .Values.backup.bucket_uri | b64enc | quote }}
