restore:
  bucket_uri: ${bucket_uri}
  db_endpoint: "${db_endpoint}"
  db_password: "${db_password}"
  db_username: "${db_username}"
  backup_file_name: "${backup_file_name}"

auth:
  username: "${db_username}"

annotations:
  ${annotations}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

restorejob:
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m
